name: CD(Dokcer Hub)
on:
  push: 

jobs:
  Dockerize:
    name: Publish Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_ACCOUNT }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      # Notice that we should use docker-hub repo name as tags, but not github repo
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: kenchen879/
cloud-computing-final-project:latest